//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorRole
    {
        public int AdministratorRoleID { get; set; }
        public int AdministratorID { get; set; }
        public int RoleID { get; set; }
        public string Group { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Role Role { get; set; }
    }
}
