//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public Administrator()
        {
            this.AdministratorRole = new HashSet<AdministratorRole>();
        }
    
        public int AdministratorID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string LastLogin { get; set; }
        public bool IsActive { get; set; }
        public string Group { get; set; }
    
        public virtual ICollection<AdministratorRole> AdministratorRole { get; set; }
    }
}
