//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.OptionDelete = new HashSet<OptionDelete>();
            this.OrderItemAttribute = new HashSet<OrderItemAttribute>();
        }
    
        public int AttributeID { get; set; }
        public int ProductID { get; set; }
        public string AttributeType { get; set; }
        public string AttributeValue { get; set; }
        public string AttributeDescription { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<OptionDelete> OptionDelete { get; set; }
        public virtual ICollection<OrderItemAttribute> OrderItemAttribute { get; set; }
    }
}
