//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public BlogPost()
        {
            this.BlogComment = new HashSet<BlogComment>();
        }
    
        public int BlogPostID { get; set; }
        public int LanguageID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public bool AllowComments { get; set; }
        public int CommentCount { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> StartDateUtc { get; set; }
        public Nullable<System.DateTime> EndDateUtc { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public bool LimitedToStores { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
    
        public virtual ICollection<BlogComment> BlogComment { get; set; }
        public virtual Language Language { get; set; }
    }
}
