//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartRole
    {
        public CartRole()
        {
            this.AclRecord = new HashSet<AclRecord>();
            this.CartUserRole = new HashSet<CartUserRole>();
            this.TierPrice = new HashSet<TierPrice>();
            this.PermissionRecord = new HashSet<PermissionRecord>();
        }
    
        public int CartRoleID { get; set; }
        public string Name { get; set; }
        public bool FreeShipping { get; set; }
        public bool TaxExempt { get; set; }
        public bool Active { get; set; }
        public bool IsSystemRole { get; set; }
        public string SystemName { get; set; }
        public int PurchasedWithProductId { get; set; }
    
        public virtual ICollection<AclRecord> AclRecord { get; set; }
        public virtual ICollection<CartUserRole> CartUserRole { get; set; }
        public virtual ICollection<TierPrice> TierPrice { get; set; }
        public virtual ICollection<PermissionRecord> PermissionRecord { get; set; }
    }
}
