//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.BasicTaxRate = new HashSet<BasicTaxRate>();
            this.State = new HashSet<State>();
            this.ShippingMethod = new HashSet<ShippingMethod>();
        }
    
        public int CountryID { get; set; }
        public string CountryFIPS { get; set; }
        public string CountryISO { get; set; }
        public string CountryTLD { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<BasicTaxRate> BasicTaxRate { get; set; }
        public virtual ICollection<State> State { get; set; }
        public virtual ICollection<ShippingMethod> ShippingMethod { get; set; }
    }
}
