//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReview
    {
        public int CustomerReviewID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Author { get; set; }
        public string ReviewSubject { get; set; }
        public string ReviewText { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> IsHelpfulYes { get; set; }
        public Nullable<int> IsHelpfulNo { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
