//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ActivityLog = new HashSet<ActivityLog>();
            this.BackInStockSubscription = new HashSet<BackInStockSubscription>();
            this.BlogComment = new HashSet<BlogComment>();
            this.CartUserClaim = new HashSet<CartUserClaim>();
            this.CartUserLogin = new HashSet<CartUserLogin>();
            this.ExternalAuthenticationRecord = new HashSet<ExternalAuthenticationRecord>();
            this.CustomerReview = new HashSet<CustomerReview>();
            this.Order = new HashSet<Order>();
            this.Forums_Post = new HashSet<Forums_Post>();
            this.Forums_Subscription = new HashSet<Forums_Subscription>();
            this.Forums_Topic = new HashSet<Forums_Topic>();
            this.Log = new HashSet<Log>();
            this.NewsComment = new HashSet<NewsComment>();
            this.PollVotingRecord = new HashSet<PollVotingRecord>();
            this.Forums_PrivateMessage = new HashSet<Forums_PrivateMessage>();
            this.Forums_PrivateMessage1 = new HashSet<Forums_PrivateMessage>();
            this.ProductReview = new HashSet<ProductReview>();
            this.ReturnRequest = new HashSet<ReturnRequest>();
            this.RewardPointsHistory = new HashSet<RewardPointsHistory>();
            this.ShoppingCartItem = new HashSet<ShoppingCartItem>();
        }
    
        public int CustomerID { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> AccountCreatedDate { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLog { get; set; }
        public virtual ICollection<BackInStockSubscription> BackInStockSubscription { get; set; }
        public virtual ICollection<BlogComment> BlogComment { get; set; }
        public virtual ICollection<CartUserClaim> CartUserClaim { get; set; }
        public virtual ICollection<CartUserLogin> CartUserLogin { get; set; }
        public virtual ICollection<ExternalAuthenticationRecord> ExternalAuthenticationRecord { get; set; }
        public virtual ICollection<CustomerReview> CustomerReview { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Forums_Post> Forums_Post { get; set; }
        public virtual ICollection<Forums_Subscription> Forums_Subscription { get; set; }
        public virtual ICollection<Forums_Topic> Forums_Topic { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<NewsComment> NewsComment { get; set; }
        public virtual ICollection<PollVotingRecord> PollVotingRecord { get; set; }
        public virtual ICollection<Forums_PrivateMessage> Forums_PrivateMessage { get; set; }
        public virtual ICollection<Forums_PrivateMessage> Forums_PrivateMessage1 { get; set; }
        public virtual ICollection<ProductReview> ProductReview { get; set; }
        public virtual ICollection<ReturnRequest> ReturnRequest { get; set; }
        public virtual ICollection<RewardPointsHistory> RewardPointsHistory { get; set; }
        public virtual ICollection<ShoppingCartItem> ShoppingCartItem { get; set; }
    }
}
