//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.BlogPost = new HashSet<BlogPost>();
            this.LocaleStringResource = new HashSet<LocaleStringResource>();
            this.LocalizedProperty = new HashSet<LocalizedProperty>();
            this.News = new HashSet<News>();
            this.Poll = new HashSet<Poll>();
        }
    
        public int LanguageID { get; set; }
        public string Name { get; set; }
        public string LanguageCulture { get; set; }
        public string UniqueSeoCode { get; set; }
        public string FlagImageFileName { get; set; }
        public bool Rtl { get; set; }
        public bool LimitedToStores { get; set; }
        public int DefaultCurrencyID { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<BlogPost> BlogPost { get; set; }
        public virtual ICollection<LocaleStringResource> LocaleStringResource { get; set; }
        public virtual ICollection<LocalizedProperty> LocalizedProperty { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Poll> Poll { get; set; }
    }
}
