//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.OrderItemAttribute = new HashSet<OrderItemAttribute>();
        }
    
        public int OptionID { get; set; }
        public int AttributeID { get; set; }
        public string OptionCode { get; set; }
        public string OptionName { get; set; }
        public string OptionDescription { get; set; }
        public bool OptionIsActive { get; set; }
        public Nullable<decimal> OptionUnitCost { get; set; }
        public Nullable<decimal> OptionUnitPrice { get; set; }
        public Nullable<decimal> OptionAltPrice { get; set; }
        public Nullable<decimal> OptionWeight { get; set; }
        public string OptionSmallImage { get; set; }
        public string OptionLargeImage { get; set; }
        public int OptionOrder { get; set; }
        public string Group { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual ICollection<OrderItemAttribute> OrderItemAttribute { get; set; }
    }
}
