//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.GiftCardUsageHistory = new HashSet<GiftCardUsageHistory>();
            this.OrderAddress1 = new HashSet<OrderAddress>();
            this.OrderDelivery = new HashSet<OrderDelivery>();
            this.OrderDiscount1 = new HashSet<OrderDiscount>();
            this.OrderItem = new HashSet<OrderItem>();
            this.Payment = new HashSet<Payment>();
            this.OrderNote = new HashSet<OrderNote>();
            this.RecurringPayment = new HashSet<RecurringPayment>();
            this.RewardPointsHistory = new HashSet<RewardPointsHistory>();
            this.Shipment = new HashSet<Shipment>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public System.Guid OrderGuid { get; set; }
        public int StoreId { get; set; }
        public bool PickUpInStore { get; set; }
        public int OrderStatusId { get; set; }
        public int OrderAddressID { get; set; }
        public int ShippingStatusId { get; set; }
        public int PaymentStatusId { get; set; }
        public string PaymentMethodSystemName { get; set; }
        public string CustomerCurrencyCode { get; set; }
        public decimal CurrencyRate { get; set; }
        public int CustomerTaxDisplayTypeId { get; set; }
        public string VatNumber { get; set; }
        public decimal OrderSubtotalInclTax { get; set; }
        public decimal OrderSubtotalExclTax { get; set; }
        public decimal OrderSubTotalDiscountInclTax { get; set; }
        public decimal OrderSubTotalDiscountExclTax { get; set; }
        public decimal OrderShippingInclTax { get; set; }
        public decimal OrderShippingExclTax { get; set; }
        public decimal PaymentMethodAdditionalFeeInclTax { get; set; }
        public decimal PaymentMethodAdditionalFeeExclTax { get; set; }
        public string TaxRates { get; set; }
        public decimal OrderTax { get; set; }
        public decimal OrderDiscount { get; set; }
        public decimal OrderTotal { get; set; }
        public decimal RefundedAmount { get; set; }
        public bool RewardPointsWereAdded { get; set; }
        public string CheckoutAttributeDescription { get; set; }
        public string CheckoutAttributesXml { get; set; }
        public int CustomerLanguageId { get; set; }
        public int AffiliateId { get; set; }
        public string CustomerIp { get; set; }
        public bool AllowStoringCreditCardNumber { get; set; }
        public string CardType { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public string MaskedCreditCardNumber { get; set; }
        public string CardCvv2 { get; set; }
        public string CardExpirationMonth { get; set; }
        public string CardExpirationYear { get; set; }
        public string AuthorizationTransactionId { get; set; }
        public string AuthorizationTransactionCode { get; set; }
        public string AuthorizationTransactionResult { get; set; }
        public string CaptureTransactionId { get; set; }
        public string CaptureTransactionResult { get; set; }
        public string SubscriptionTransactionId { get; set; }
        public Nullable<System.DateTime> PaidDateUtc { get; set; }
        public string ShippingMethod { get; set; }
        public string ShippingRateComputationMethodSystemName { get; set; }
        public string CustomValuesXml { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<GiftCardUsageHistory> GiftCardUsageHistory { get; set; }
        public virtual OrderAddress OrderAddress { get; set; }
        public virtual ICollection<OrderAddress> OrderAddress1 { get; set; }
        public virtual ICollection<OrderDelivery> OrderDelivery { get; set; }
        public virtual ICollection<OrderDiscount> OrderDiscount1 { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual ICollection<OrderNote> OrderNote { get; set; }
        public virtual ICollection<RecurringPayment> RecurringPayment { get; set; }
        public virtual ICollection<RewardPointsHistory> RewardPointsHistory { get; set; }
        public virtual ICollection<Shipment> Shipment { get; set; }
    }
}
