//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemAttribute
    {
        public int OrderItemAttributeID { get; set; }
        public Nullable<int> OrderItemID { get; set; }
        public Nullable<int> AttributeID { get; set; }
        public Nullable<int> OptionID { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual OptionDelete OptionDelete { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
