//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollAnswer
    {
        public PollAnswer()
        {
            this.PollVotingRecord = new HashSet<PollVotingRecord>();
        }
    
        public int PollAnswerID { get; set; }
        public int PollID { get; set; }
        public string Name { get; set; }
        public int NumberOfVotes { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual Poll Poll { get; set; }
        public virtual ICollection<PollVotingRecord> PollVotingRecord { get; set; }
    }
}
