//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecificationAttribute
    {
        public int ProductSpecificationAttributeID { get; set; }
        public Nullable<int> ProductSpecificationID { get; set; }
        public string AttributeKey { get; set; }
        public string AttributeValue { get; set; }
    
        public virtual ProductSpecification ProductSpecification { get; set; }
    }
}
