//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRating
    {
        public int ProductRatingID { get; set; }
        public int ProductID { get; set; }
        public string ProductRatingDescription { get; set; }
        public byte AverageProductRating { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
