//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProductAttributeMapping
    {
        public ProductProductAttributeMapping()
        {
            this.ProductAttributeValue = new HashSet<ProductAttributeValue>();
        }
    
        public int ProductProductAttributeMappingID { get; set; }
        public int ProductID { get; set; }
        public int ProductAttributeID { get; set; }
        public string TextPrompt { get; set; }
        public bool IsRequired { get; set; }
        public int AttributeControlTypeId { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> ValidationMinLength { get; set; }
        public Nullable<int> ValidationMaxLength { get; set; }
        public string ValidationFileAllowedExtensions { get; set; }
        public Nullable<int> ValidationFileMaximumSize { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductAttribute ProductAttribute { get; set; }
        public virtual ICollection<ProductAttributeValue> ProductAttributeValue { get; set; }
    }
}
