//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecification
    {
        public ProductSpecification()
        {
            this.ProductSpecificationAttribute = new HashSet<ProductSpecificationAttribute>();
        }
    
        public int ProductSpecificationID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> ProductSpecificationOrder { get; set; }
        public string ProductSpecificationHeader { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductSpecificationAttribute> ProductSpecificationAttribute { get; set; }
    }
}
