//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWarehouseInventory
    {
        public int ProductWarehouseInventoryID { get; set; }
        public int ProductID { get; set; }
        public int WarehouseID { get; set; }
        public int StockQuantity { get; set; }
        public int ReservedQuantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
