//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringPayment
    {
        public RecurringPayment()
        {
            this.RecurringPaymentHistory = new HashSet<RecurringPaymentHistory>();
        }
    
        public int RecurringPaymentID { get; set; }
        public int CycleLength { get; set; }
        public int CyclePeriodID { get; set; }
        public int TotalCycles { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public bool IsActive { get; set; }
        public bool Deleted { get; set; }
        public int InitialOrderID { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<RecurringPaymentHistory> RecurringPaymentHistory { get; set; }
    }
}
