//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistory
    {
        public int SalesHistoryID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CustomerAddressID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<int> SalesReturns { get; set; }
        public Nullable<decimal> SalesCost { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
