//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingByWeight
    {
        public int ShippingByWeightID { get; set; }
        public int StoreID { get; set; }
        public int CountryID { get; set; }
        public int StateProvinceID { get; set; }
        public string Zip { get; set; }
        public int ShippingMethodID { get; set; }
        public decimal From { get; set; }
        public decimal To { get; set; }
        public decimal AdditionalFixedCost { get; set; }
        public decimal PercentageRateOfSubtotal { get; set; }
        public decimal RatePerWeightUnit { get; set; }
        public decimal LowerWeightLimit { get; set; }
    }
}
