//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingRate
    {
        public int ShippingRateID { get; set; }
        public int ShippingMethodID { get; set; }
        public decimal Floor { get; set; }
        public decimal Ceiling { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public string Group { get; set; }
    
        public virtual ShippingMethod ShippingMethod { get; set; }
    }
}
