//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentItem
    {
        public int ShipmentItemID { get; set; }
        public int ShipmentID { get; set; }
        public int OrderItemID { get; set; }
        public int Quantity { get; set; }
        public int WarehouseID { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
