//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkuDiscount
    {
        public int SkuDiscountID { get; set; }
        public int SkuID { get; set; }
        public int DiscountID { get; set; }
        public string Group { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Sku Sku { get; set; }
    }
}
