//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.BasicTaxRate = new HashSet<BasicTaxRate>();
            this.City = new HashSet<City>();
        }
    
        public int StateID { get; set; }
        public int CountryID { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
    
        public virtual ICollection<BasicTaxRate> BasicTaxRate { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual Country Country { get; set; }
    }
}
