//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate
    {
        public int TaxRateID { get; set; }
        public int StoreID { get; set; }
        public int TaxCategoryID { get; set; }
        public int CountryID { get; set; }
        public int StateProvinceID { get; set; }
        public string Zip { get; set; }
        public decimal Percentage { get; set; }
    }
}
